namespace ECommerceAPI.Infrastructure.Operations;

public static class NameOperation
{
	public static string CharacterRegulatory(string name)
		=> name.Replace("é", "")
				.Replace("!", "")
				.Replace("'", "")
				.Replace("^", "")
				.Replace("+", "")
				.Replace("%", "")
				.Replace("&", "")
				.Replace("/", "")
				.Replace("(", "")
				.Replace(")", "")
				.Replace("=", "")
				.Replace("?", "")
				.Replace("_", "")
				.Replace("<", "")
				.Replace(">", "")
				.Replace("|", "")
				.Replace("#", "")
				.Replace("$", "")
				.Replace("{", "")
				.Replace("[", "")
				.Replace("]", "")
				.Replace("]", "")
				.Replace("}", "")
				.Replace("-", "")
				.Replace("ğ", "g")
				.Replace("Ğ", "g")
				.Replace("Ü", "u")
				.Replace("ü", "u")
				.Replace("Ş", "s")
				.Replace("ş", "s")
				.Replace("İ", "i")
				.Replace("I", "i")
				.Replace("Ö", "o")
				.Replace("ö", "o")
				.Replace("Ç", "c")
				.Replace("ç", "c");
}
